Problem 1
```{r}
df <- data.frame(
  Month = sample(3:12, size = 100, replace = T),
  Day = sample(1:30, size = 100, replace = T),
  Year = sample(2000:2020, size = 100, replace = T)
)
```

Problem 2
```{r}
df[1,"Month"] <- 4    #Method 1 accesses data frame element directly
df$Month[1]   <- 4

df[1,"Day"] <- 24
```

Problem 3
```{r}
df$Day[1] <- 24
```

Problem 4
```{r}
df[1,"Year"] <- 2019
```

Problem 5
```{r}
df$Year[1] <- 2019
```

Problem 6
```{r}
X <- df$Year %/% 100
```

Problem 7
```{r}
Y <- df$Year %% 100
```

Problem 8
```{r}
M <- df$Month
D <- df$Day
X <- df$Year %/% 100
Y <- df$Year %% 100

df$Weekday <- (D + (5*X) + Y + floor(((13*M) - 27) / 5) + floor(X / 4) + floor(Y / 4))%% 7
```

Problem 9
```{r}
M <- df$Month
D <- df$Day
X <- df$Year %/% 100
Y <- df$Year %% 100

df$Weekday <- (D + (5*X) + Y + (((13*M) - 27) %/% 5) + (X %/% 4) + (Y %/% 4))%% 7
```

Problem 10
```{r}
df$Weekday <- factor(df$Weekday)
levels(df$Weekday) <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
```

Problem 11
```{r}
print(df[1, "Weekday"])
```
Problem 12
```{r}
df <- data.frame(
  Month = sample(1:12,      size=100, replace=T),
  Day   = sample(1:30,      size=100, replace=T),
  Year  = sample(1700:2018, size=100, replace=T)
)


```

Problem 12 cont
```{r}
df$Day <- ifelse(df$Month==2 & df$Day > 28, sample(1:28,size=1),                df$Day)


df$Day[df$Month == 2]
```

Problem 14
```{r}
M <- ifelse(df$Month > 2, df$Month, df$Month + 12)
```

Problem 15
```{r}
M <- ifelse(df$Month > 2, df$Month, df$Month+12)
D <- ifelse(df$Month==2 & df$Day > 28, sample(1:28,size=1), df$Day)
X <- df$Year %/% 100
Y <- df$Year %% 100

df$Weekday <- (D + 5*X + Y + (13*M-27) %/% 5 + X%/%4 + Y%/%4) %% 7
df$Weekday <- factor(df$Weekday)
levels(df$Weekday) <- c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")

```

Problem 16
```{r}
n <- 17
message <- ifelse(n%%4 == 0 ,"n is divisible by 4", "n is not divisible by 4")
print(message)

```
Problem 17
```{r}
df$LeapYear <- ifelse(df$Year %% 400 == 0, "Yes",
                      ifelse(df$Year %% 100 == 0, "No",
                      ifelse(df$Year %% 4 == 0, "Yes", "No")))
```
