Problem 1
```{r}
rev(mtcars$hp)
```
Problem 2
```{r}
horsepower <- mtcars$hp
rev(horsepower)
horsepower
```
Problem 3
```{r}
sample(mtcars$mpg, 12)
```
Problem 4
```{r}
v <- 1:10
sample(v, 5)
```
Problem 5
```{r}
sort(unique(mtcars$carb))
```
Problem 6
```{r}
unique(mtcars$gear)
```
Problem 8
```{r}
table(mtcars$cyl)
```
Problem 9
```{r}
table(mtcars$carb, mtcars$cyl)
```
Problem 10
```{r}
seq(2, 100, 2)
```
Problem 11
```{r}
seq(23, 37, length.out = 100)
```
Problem 12
```{r}
rep(0, 100)
```
Problem 13
```{r}
mtcars$wt[1:12]
```
Problem 14
```{r}
mtcars$wt[c(1,3,5)]
```
Problem 15
```{r}
mtcars$mpg[1:9] <- round(mtcars$mpg[1:9])

mtcars$mpg[1:9]
```

Problem 16
```{r}
half <- length(mtcars$disp) / 2
end <- length(mtcars$disp)

mtcars$disp[half:end] <- round(mtcars$disp[half:end])
```

Problem 17
```{r}
df <- mtcars
n <- nrow(df)
df$order <- 1:n

mtcars$class <- c("class 1", "class 2", "class 3", "class 4")
mtcars$class <- rep(c("class 1", "class 2", "class 3", "class 4"), each = 8)

```

Problem 18
```{r}
mtcars$uniqueid <- sample(1:32, replace = F)
mtcars
```

Problem 19
```{r}
mtcars$am[mtcars$am == 0] <- "automatic"
mtcars$am[mtcars$am == 1] <- "manual"
```

Problem 20
```{r}

```

