```{r}
dodgers_2_ %>% 
  mutate(month       = factor(month,       levels = c("APR","MAY","JUN","JUL","AUG","SEP","OCT")),
         day_of_week = factor(day_of_week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday",
                                                      "Friday", "Saturday", "Sunday"))) -> wc

```

```{r}
wc %>%
  ggplot(aes(x = bobblehead, y = attend)) +
   geom_boxplot()
```
```{r}
wc %>%
  group_by(bobblehead) %>%
  summarize(Median = median(attend))
```

```{r}
wc %>%
  count(bobblehead, name = "Freq")
```

```{r}
wc %>% 
  filter(day_of_week == "Tuesday" |
         day_of_week == "Thursday"|
         day_of_week == "Saturday"|
         day_of_week == "Sunday")              %>% 
  group_by(day_of_week, bobblehead)            %>% 
  summarize(MedianAttendance = median(attend)) %>% 
  ggplot(aes(x = day_of_week, 
             y = MedianAttendance)) +
     geom_col(aes(fill=bobblehead), 
              position = "dodge")

```

```{r}
wc %>% 
  filter(day_of_week == "Tuesday" |
         day_of_week == "Thursday"|
         day_of_week == "Saturday"|
         day_of_week == "Sunday")              %>% 
  group_by(day_night, bobblehead)              %>% 
  summarize(MedianAttendance = median(attend)) %>% 
  ggplot(aes(x = day_night, y = MedianAttendance)) +
     geom_col(aes(fill=bobblehead), 
              position = "dodge")

```

```{r}
wc %>% 
  filter(day_of_week == "Tuesday" |
         day_of_week == "Thursday"|
         day_of_week == "Saturday"|
         day_of_week == "Sunday")              %>% 
  group_by(skies, bobblehead)              %>% 
  summarize(MedianAttendance = median(attend)) %>% 
  ggplot(aes(x = skies, y = MedianAttendance)) +
     geom_col(aes(fill=bobblehead), 
              position = "dodge")

```

```{r}
wc %>% 
  filter(day_of_week == "Tuesday" |
         day_of_week == "Thursday"|
         day_of_week == "Saturday"|
         day_of_week == "Sunday")              %>% 
  group_by(month, bobblehead)              %>% 
  summarize(MedianAttendance = median(attend)) %>% 
  ggplot(aes(x = MedianAttendance, y = month)) +
     geom_col(aes(fill=bobblehead), 
              position = "dodge")
```

